# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 424a18d3adab1a9913310a9ccea10beb8d22ff7624519cd716ee4bc5be0a32d2aa40c45e6a6ba2b5f12d8b7f69c141de01d245ad92a0674bd99152529d0f3e6c

test:
  secret_key_base: ba8099c69b1477e9376ec5fef0a0636a53e881d0950aec8c1ecafdebb01f8b02f35b888365515a7506618fbbdf24071d8ce1fe3554656fecc7a2b61410db53c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
